### ISSUE TITLE
Cannot be used with gnu coreutils

### ISSUE THREAD

**Issue by OrcaXS** [derekstavis/touchrunner#2]
If I add gnu coreutils to `fish_user_paths` by `set --universal fish_user_paths (brew --prefix coreutils)/libexec/gnubin $fish_user_paths`, 
`stat: cannot read file system information for '%m': No such file or directory ` error would be thrown every time entering a npm project directory.

**Comment by derekstavis** [comment]
Whoa, 2 years later here I am replying to this one. Overall I think that replacing BSD by GNU coreutils is a bad idea since many other tools will assume that because you run macOS the expected coreutils are BSD ones and not GNU. I think that Oh My Fish itself tests for the platform using `uname` and branches off how to use tools like `sed` depending on that, so having GNU coreutils would break this assumption. I'd recommend using the prefixed versions of coreutils instead -- `gsed`, etc
